// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKFL86m14Y0qqhAd2Hq-KuewaxKIySIvw',
    appId: '1:389591333547:web:2dbcdeb328949fcad855ee',
    messagingSenderId: '389591333547',
    projectId: 'mentraverse-app',
    authDomain: 'mentraverse-app.firebaseapp.com',
    storageBucket: 'mentraverse-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpDT3hZJEJWSjGjjI4khCHpclPtwMoe0k',
    appId: '1:389591333547:android:c4fa05cb8fee20a6d855ee',
    messagingSenderId: '389591333547',
    projectId: 'mentraverse-app',
    storageBucket: 'mentraverse-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacKx8X5ZhjPEv5h3usYRmVRRRU7LrN6k',
    appId: '1:389591333547:ios:68b5cb340c208bc1d855ee',
    messagingSenderId: '389591333547',
    projectId: 'mentraverse-app',
    storageBucket: 'mentraverse-app.firebasestorage.app',
    iosBundleId: 'com.example.mentraverseFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacKx8X5ZhjPEv5h3usYRmVRRRU7LrN6k',
    appId: '1:389591333547:ios:68b5cb340c208bc1d855ee',
    messagingSenderId: '389591333547',
    projectId: 'mentraverse-app',
    storageBucket: 'mentraverse-app.firebasestorage.app',
    iosBundleId: 'com.example.mentraverseFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKFL86m14Y0qqhAd2Hq-KuewaxKIySIvw',
    appId: '1:389591333547:web:d32fc8078dc00a69d855ee',
    messagingSenderId: '389591333547',
    projectId: 'mentraverse-app',
    authDomain: 'mentraverse-app.firebaseapp.com',
    storageBucket: 'mentraverse-app.firebasestorage.app',
  );

}